import streamlit as st

st.set_page_config(page_title="About", page_icon=":books:")
st.title('RAGQuest: Book Inquiry Engine using LangChain 🦜🔗')
st.header('About')
st.markdown("""
    <div style="text-align: justify">
    RAGNify is a web-based Book Knowledge Portal that leverages the power of Retrieval-Augmented Generation (RAG) models
    for question answering. It integrates the LangChain library, which provides tools for natural language processing
    tasks, and utilizes the LLM OpenAI model for language generation and embedding.
    </div>
    """, unsafe_allow_html=True)


st.subheader("Personal Purpose: :dart:")
st.markdown("""
            <div style="text-align: justify">
            The primary personal purpose of the RAGNify Book Knowledge Portal is to serve as a showcase of my skills
            and expertise in utilizing Large Language Models (LLMs), Python programming, LangChain library, and other
            advanced technologies. By developing this project, I aim to demonstrate my proficiency in building sophisticated
            natural language processing systems that leverage cutting-edge techniques to provide valuable services to users.

            Additionally, I intend to highlight my ability to design and implement user-friendly interfaces, integrate
            diverse libraries and APIs seamlessly, and deliver comprehensive solutions that address real-world needs.
            This project not only showcases my technical capabilities but also reflects my passion for knowledge dissemination,
            education, and innovation in the field of artificial intelligence and natural language understanding.
            <div style="text-align: justify">
            """, unsafe_allow_html=True)


# Key Features Section

st.subheader("Key Features: :closed_lock_with_key:")
st.markdown("""
- **RAG-based Question Answering:** Users can ask questions about two books, such as 'The Genetic Effects of Radiation',
    by Isaac Asimov and 'Pride and Prejudice', by Jane Austen, and receive answers generated by the RAG model.
- **Book Selection:** The portal allows users to select the book they want to inquire about from a list of available options.
- **Streamlit UI:** The project features a user-friendly interface built using Streamlit, enabling easy interaction with the system.
- **LangChain Integration:** LangChain library is seamlessly integrated into the project, providing functionalities for text processing,
    embedding generation, and more.
- **LLM OpenAI Model:** The project utilizes the LLM (Large Language Model) from OpenAI for language generation tasks and embedding,
    ensuring high-quality responses to user queries.
""")


st.subheader("Benefits")
st.markdown("""
- **Efficient Information Retrieval:** Users can quickly access information from books by asking questions, allowing for efficient learning and research.
- **Comprehensive Coverage:** The portal supports multiple books, providing users with a wide range of literary works to inquire about, enhancing their understanding and exploration of various topics.
- **User-Friendly Interface:** With its Streamlit UI, the portal offers a user-friendly experience, making it accessible to users with varying levels of technical expertise.
- **Integration of Advanced Technologies:** By integrating **LangChain** library and the LLM **OpenAI** model, the project leverages cutting-edge natural language processing techniques, ensuring high-quality responses and advanced functionalities.
- **Enhanced Research Capabilities:** Researchers, students, and enthusiasts can benefit from the portal's advanced search capabilities, enabling them to conduct in-depth analysis and exploration of literary works.
- **Time and Resource Savings:** The portal streamlines the process of information retrieval, saving users time and resources that would otherwise be spent manually searching through books or conducting extensive research.
- **Educational Value:** RAGNify not only provides answers to user queries but also facilitates learning and knowledge acquisition by presenting information in a clear and concise manner, fostering intellectual growth and curiosity.
""", unsafe_allow_html=True)
